name: Notify Slack on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  notify-slack:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && success()) ||
      (github.event_name == 'push' && success())
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changes
        id: get-changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Get PR changes
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
            DESCRIPTION="${{ github.event.pull_request.body }}"
            TITLE="${{ github.event.pull_request.title }}"
            AUTHOR="${{ github.event.pull_request.user.login }}"
            URL="${{ github.event.pull_request.html_url }}"
          else
            # Get push changes
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
            DESCRIPTION="${{ github.event.head_commit.message }}"
            TITLE="${{ github.event.head_commit.message }}"
            AUTHOR="${{ github.event.head_commit.author.username }}"
            URL="${{ github.event.head_commit.url }}"
          fi
          
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "$DESCRIPTION" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "author=$AUTHOR" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Send to Slack
        if: success()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ vars.SLACK_CHANNEL_ID }}
            text: "GitHub Action build result: ${{ job.status }}\n${{ steps.get-changes.outputs.url }}"
            blocks:
              - type: header
                text:
                  type: plain_text
                  text: "🎉 Repo Updated! 🎉"
                  emoji: true
              - type: section
                text:
                  type: mrkdwn
                  text: |
                    *Title:* ${{ steps.get-changes.outputs.title }}
                    *Author:* ${{ steps.get-changes.outputs.author }}
                    *URL:* ${{ steps.get-changes.outputs.url }}
              - type: section
                text:
                  type: mrkdwn
                  text: |
                    *Description:*
                    ${{ steps.get-changes.outputs.description }}
              - type: section
                text:
                  type: mrkdwn
                  text: |
                    *Changed Files:*
                    ```${{ steps.get-changes.outputs.changed_files }}```
